# Generated by Django 5.0.1 on 2025-12-10 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="Nombre de la universidad o institución",
                        max_length=200,
                        verbose_name="institución",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("high_school", "Bachillerato"),
                            ("technical", "Técnico"),
                            ("technology", "Tecnología"),
                            ("bachelor", "Pregrado/Licenciatura"),
                            ("master", "Maestría"),
                            ("phd", "Doctorado"),
                            ("certificate", "Certificación"),
                            ("diploma", "Diplomado"),
                        ],
                        max_length=50,
                        verbose_name="título",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: Ingeniería de Sistemas, Administración",
                        max_length=100,
                        verbose_name="campo de estudio",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de finalización"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="¿Estás estudiando actualmente aquí?",
                        verbose_name="actual",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: 9.5/10, Cum Laude, etc.",
                        max_length=50,
                        verbose_name="calificación",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Actividades, logros, proyectos destacados",
                        max_length=500,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "educación",
                "verbose_name_plural": "educación",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="visibilidad del perfil",
                    ),
                ),
                (
                    "email_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="visibilidad del email",
                    ),
                ),
                (
                    "phone_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="visibilidad del teléfono",
                    ),
                ),
                (
                    "birth_date_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="friends",
                        max_length=20,
                        verbose_name="visibilidad de fecha de nacimiento",
                    ),
                ),
                (
                    "default_post_privacy",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="friends",
                        help_text="Privacidad predeterminada para nuevos posts",
                        max_length=20,
                        verbose_name="privacidad por defecto de posts",
                    ),
                ),
                (
                    "friend_list_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="friends",
                        max_length=20,
                        verbose_name="visibilidad de lista de amigos",
                    ),
                ),
                (
                    "who_can_message",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="friends",
                        max_length=20,
                        verbose_name="quién puede enviar mensajes",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="notificaciones por email"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="notificaciones push"
                    ),
                ),
                (
                    "friend_request_notifications",
                    models.BooleanField(
                        default=True, verbose_name="notificar solicitudes de amistad"
                    ),
                ),
                (
                    "post_like_notifications",
                    models.BooleanField(
                        default=True, verbose_name='notificar "me gusta" en posts'
                    ),
                ),
                (
                    "comment_notifications",
                    models.BooleanField(
                        default=True, verbose_name="notificar comentarios"
                    ),
                ),
                (
                    "mention_notifications",
                    models.BooleanField(
                        default=True, verbose_name="notificar menciones"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración de privacidad",
                "verbose_name_plural": "configuraciones de privacidad",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Cuéntanos sobre ti (máximo 500 caracteres)",
                        max_length=500,
                        verbose_name="biografía",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Masculino"),
                            ("female", "Femenino"),
                            ("other", "Otro"),
                            ("prefer_not_to_say", "Prefiero no decir"),
                        ],
                        max_length=20,
                        verbose_name="género",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad, País",
                        max_length=100,
                        verbose_name="ubicación",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="sitio web")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de perfil (recomendado: 500x500px)",
                        null=True,
                        upload_to="profiles/%Y/%m/",
                        verbose_name="foto de perfil",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de portada (recomendado: 1200x400px)",
                        null=True,
                        upload_to="covers/%Y/%m/",
                        verbose_name="foto de portada",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter/X")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                (
                    "posts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="publicaciones"
                    ),
                ),
                (
                    "friends_count",
                    models.PositiveIntegerField(default=0, verbose_name="amigos"),
                ),
                (
                    "followers_count",
                    models.PositiveIntegerField(default=0, verbose_name="seguidores"),
                ),
                (
                    "following_count",
                    models.PositiveIntegerField(default=0, verbose_name="siguiendo"),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado, solo tus amigos pueden ver tu perfil",
                        verbose_name="perfil público",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False,
                        help_text="Mostrar email en el perfil público",
                        verbose_name="mostrar email",
                    ),
                ),
                (
                    "show_phone",
                    models.BooleanField(
                        default=False,
                        help_text="Mostrar teléfono en el perfil público",
                        verbose_name="mostrar teléfono",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de usuario",
                "verbose_name_plural": "perfiles de usuario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="Nombre de la empresa u organización",
                        max_length=200,
                        verbose_name="empresa",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Ejemplo: Desarrollador Full Stack, Gerente de Marketing",
                        max_length=100,
                        verbose_name="cargo",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Tiempo completo"),
                            ("part_time", "Medio tiempo"),
                            ("freelance", "Freelance"),
                            ("internship", "Pasantía"),
                            ("contract", "Contrato"),
                            ("volunteer", "Voluntariado"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="tipo de empleo",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text='Ciudad, País o "Remoto"',
                        max_length=100,
                        verbose_name="ubicación",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de finalización"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="¿Trabajas actualmente aquí?",
                        verbose_name="trabajo actual",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Responsabilidades, logros, proyectos destacados",
                        max_length=1000,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "experiencia laboral",
                "verbose_name_plural": "experiencia laboral",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="visto en"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="dirección IP"
                    ),
                ),
                (
                    "viewed_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="perfil visitado",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="visitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita de perfil",
                "verbose_name_plural": "visitas de perfil",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["viewed_profile", "-viewed_at"],
                        name="profiles_pr_viewed__65e5f2_idx",
                    ),
                    models.Index(
                        fields=["viewer", "-viewed_at"],
                        name="profiles_pr_viewer__98ba23_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ejemplo: Python, Photoshop, Marketing Digital",
                        max_length=100,
                        verbose_name="habilidad",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                            ("expert", "Experto"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="nivel",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="años de experiencia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "habilidad",
                "verbose_name_plural": "habilidades",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
