# Generated by Django 5.0.1 on 2025-12-11 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "reacción",
                "verbose_name_plural": "reacciones",
            },
        ),
        migrations.AddField(
            model_name="like",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍 Me gusta"),
                    ("love", "❤️ Me encanta"),
                    ("haha", "😂 Me divierte"),
                    ("wow", "😮 Me asombra"),
                    ("sad", "😢 Me entristece"),
                    ("angry", "😠 Me enoja"),
                ],
                default="like",
                max_length=10,
                verbose_name="tipo de reacción",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["reaction_type"], name="likes_like_reactio_128b23_idx"
            ),
        ),
    ]
