# Generated by Django 5.0.1 on 2025-12-11 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Acoso"),
                            ("inappropriate", "Contenido inapropiado"),
                            ("fake", "Perfil falso"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="razón",
                    ),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="bloqueado en"
                    ),
                ),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bloqueado",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bloqueador",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario bloqueado",
                "verbose_name_plural": "usuarios bloqueados",
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["blocker", "-blocked_at"],
                        name="friends_blo_blocker_88247f_idx",
                    ),
                    models.Index(
                        fields=["blocked", "-blocked_at"],
                        name="friends_blo_blocked_bd0502_idx",
                    ),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje opcional de presentación",
                        max_length=200,
                        verbose_name="mensaje",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo el destinatario vio la solicitud",
                        null=True,
                        verbose_name="visto en",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo se respondió a la solicitud",
                        null=True,
                        verbose_name="respondido en",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="de usuario",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="para usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud de amistad",
                "verbose_name_plural": "solicitudes de amistad",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_user", "status", "-created_at"],
                        name="friends_fri_to_user_63f4e3_idx",
                    ),
                    models.Index(
                        fields=["from_user", "status", "-created_at"],
                        name="friends_fri_from_us_7768d4_idx",
                    ),
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_as_user1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario 1",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_as_user2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "amistad",
                "verbose_name_plural": "amistades",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user1", "-created_at"],
                        name="friends_fri_user1_i_97c05b_idx",
                    ),
                    models.Index(
                        fields=["user2", "-created_at"],
                        name="friends_fri_user2_i_8341f4_idx",
                    ),
                ],
                "unique_together": {("user1", "user2")},
            },
        ),
        migrations.CreateModel(
            name="FriendSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("mutual_friends", "Amigos en común"),
                            ("same_career", "Misma carrera"),
                            ("same_semester", "Mismo semestre"),
                            ("common_interests", "Intereses comunes"),
                            ("common_groups", "Grupos en común"),
                            ("profile_view", "Visitó tu perfil"),
                            ("other", "Otro"),
                        ],
                        default="mutual_friends",
                        max_length=30,
                        verbose_name="razón",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Puntuación de relevancia de la sugerencia (0-1)",
                        verbose_name="puntuación",
                    ),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="El usuario descartó esta sugerencia",
                        verbose_name="descartada",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="descartada en"
                    ),
                ),
                (
                    "suggested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario sugerido",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "sugerencia de amistad",
                "verbose_name_plural": "sugerencias de amistad",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-score", "-created_at"],
                        name="friends_fri_user_id_e96a48_idx",
                    )
                ],
                "unique_together": {("user", "suggested_user")},
            },
        ),
    ]
