# Generated by Django 5.0.1 on 2025-12-10 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={
                            "unique": "Ya existe un usuario con este email."
                        },
                        max_length=255,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "Ya existe un usuario con este nombre de usuario."
                        },
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El username debe tener entre 3-30 caracteres. Solo letras, números, guiones y guiones bajos.",
                                regex="^[a-zA-Z0-9_-]{3,30}$",
                            )
                        ],
                        verbose_name="nombre de usuario",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="nombre")),
                ("last_name", models.CharField(max_length=50, verbose_name="apellido")),
                (
                    "career",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sistemas", "Ingeniería en Sistemas"),
                            ("software", "Ingeniería en Software"),
                            ("electronica", "Ingeniería Electrónica"),
                            ("comercio", "Comercio Exterior"),
                            ("turismo", "Turismo"),
                            ("agroindustria", "Agroindustria"),
                            ("enfermeria", "Enfermería"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="carrera",
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Semestre actual del estudiante",
                        null=True,
                        verbose_name="semestre",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="Código único de estudiante de UPEC",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="código de estudiante",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("student", "Estudiante"),
                            ("teacher", "Docente"),
                            ("admin", "Administrativo"),
                            ("graduate", "Egresado"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="tipo de usuario",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="teléfono"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designa si este usuario debe ser tratado como activo.",
                        verbose_name="activo",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designa si el usuario puede entrar al sitio de administración.",
                        verbose_name="staff",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designa si el usuario ha verificado su email.",
                        verbose_name="verificado",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de registro",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último inicio de sesión"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Los grupos a los que pertenece este usuario.",
                        related_name="uniconet_users",
                        related_query_name="uniconet_user",
                        to="auth.group",
                        verbose_name="grupos",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permisos específicos para este usuario.",
                        related_name="uniconet_users",
                        related_query_name="uniconet_user",
                        to="auth.permission",
                        verbose_name="permisos de usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="token"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expira")),
                ("is_used", models.BooleanField(default=False, verbose_name="usado")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="usado en"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="authentication.user",
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "token de recuperación de contraseña",
                "verbose_name_plural": "tokens de recuperación de contraseña",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="hora de inicio"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Información del navegador",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("desktop", "Escritorio"),
                            ("mobile", "Móvil"),
                            ("tablet", "Tablet"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="tipo de dispositivo",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad, País",
                        max_length=100,
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el inicio de sesión fue exitoso",
                        verbose_name="exitoso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to="authentication.user",
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de inicio de sesión",
                "verbose_name_plural": "historial de inicios de sesión",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="token"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expira")),
                ("is_used", models.BooleanField(default=False, verbose_name="usado")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="usado en"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to="authentication.user",
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "token de verificación de email",
                "verbose_name_plural": "tokens de verificación de email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Académico"),
                            ("sports", "Deportes"),
                            ("arts", "Arte y Cultura"),
                            ("technology", "Tecnología"),
                            ("music", "Música"),
                            ("travel", "Viajes"),
                            ("food", "Gastronomía"),
                            ("reading", "Lectura"),
                            ("gaming", "Videojuegos"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ejemplo: Programación, Fútbol, Fotografía",
                        max_length=100,
                        verbose_name="nombre del interés",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del interés",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="authentication.user",
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "interés",
                "verbose_name_plural": "intereses",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="authenticat_email_d74434_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="authenticat_usernam_61ef80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="authenticat_is_acti_8e3a98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "-login_time"], name="authenticat_user_id_c044df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinterest",
            unique_together={("user", "name")},
        ),
    ]
