# Generated by Django 5.0.1 on 2025-12-11 02:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "posts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="publicaciones"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="último uso"),
                ),
            ],
            options={
                "verbose_name": "hashtag",
                "verbose_name_plural": "hashtags",
                "ordering": ["-posts_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Escribe algo...",
                        max_length=5000,
                        verbose_name="contenido",
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Público"),
                            ("friends", "Solo amigos"),
                            ("private", "Solo yo"),
                        ],
                        default="friends",
                        max_length=20,
                        verbose_name="privacidad",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad, País",
                        max_length=200,
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "feeling",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "😊 Feliz"),
                            ("excited", "🤩 Emocionado"),
                            ("loved", "🥰 Enamorado"),
                            ("sad", "😢 Triste"),
                            ("angry", "😠 Enojado"),
                            ("tired", "😴 Cansado"),
                            ("blessed", "🙏 Bendecido"),
                            ("motivated", "💪 Motivado"),
                            ("grateful", "🙌 Agradecido"),
                            ("confused", "😕 Confundido"),
                        ],
                        max_length=50,
                        verbose_name="sentimiento",
                    ),
                ),
                (
                    "has_images",
                    models.BooleanField(default=False, verbose_name="tiene imágenes"),
                ),
                (
                    "has_videos",
                    models.BooleanField(default=False, verbose_name="tiene videos"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="me gusta"),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(default=0, verbose_name="comentarios"),
                ),
                (
                    "shares_count",
                    models.PositiveIntegerField(default=0, verbose_name="compartidos"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="editado"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="fijado"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="archivado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="editado en"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "shared_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="posts.post",
                        verbose_name="post compartido",
                    ),
                ),
            ],
            options={
                "verbose_name": "publicación",
                "verbose_name_plural": "publicaciones",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtag_posts",
                        to="posts.hashtag",
                        verbose_name="hashtag",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_hashtags",
                        to="posts.post",
                        verbose_name="publicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "hashtag de publicación",
                "verbose_name_plural": "hashtags de publicación",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="posts/images/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                        verbose_name="imagen",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Orden de visualización de la imagen",
                        verbose_name="orden",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.post",
                        verbose_name="publicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de publicación",
                "verbose_name_plural": "imágenes de publicación",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PostMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="posts.post",
                        verbose_name="publicación",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentioned_in_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario mencionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "mención en publicación",
                "verbose_name_plural": "menciones en publicaciones",
            },
        ),
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Acoso"),
                            ("hate_speech", "Discurso de odio"),
                            ("violence", "Violencia"),
                            ("nudity", "Desnudez o contenido sexual"),
                            ("false_info", "Información falsa"),
                            ("self_harm", "Autolesión o suicidio"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="razón",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detalles adicionales del reporte",
                        max_length=500,
                        verbose_name="descripción",
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, verbose_name="revisado"),
                ),
                ("is_valid", models.BooleanField(default=False, verbose_name="válido")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revisado en"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="posts.post",
                        verbose_name="publicación",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reportador",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de publicación",
                "verbose_name_plural": "reportes de publicaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="posts/videos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "wmv",
                                    "flv",
                                    "webm",
                                ]
                            )
                        ],
                        verbose_name="video",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posts/thumbnails/%Y/%m/%d/",
                        verbose_name="miniatura",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración en segundos",
                        null=True,
                        verbose_name="duración",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="posts.post",
                        verbose_name="publicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "video de publicación",
                "verbose_name_plural": "videos de publicación",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="posts_post_author__f8ea20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["privacy", "-created_at"], name="posts_post_privacy_37b119_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="posts_post_created_183a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posthashtag",
            index=models.Index(
                fields=["hashtag", "-created_at"], name="posts_posth_hashtag_2ef953_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="posthashtag",
            unique_together={("post", "hashtag")},
        ),
        migrations.AddIndex(
            model_name="postmention",
            index=models.Index(
                fields=["user", "-created_at"], name="posts_postm_user_id_c27c64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postmention",
            unique_together={("post", "user")},
        ),
        migrations.AddIndex(
            model_name="postreport",
            index=models.Index(
                fields=["is_reviewed", "-created_at"],
                name="posts_postr_is_revi_a4699d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postreport",
            unique_together={("post", "reporter")},
        ),
    ]
